# Generated by Django 5.0.1 on 2024-01-12 01:09

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Plot', models.CharField(default='NULL', max_length=500)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('sci-fi', 'Science Fiction'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('romance', 'Romance')], max_length=1000)),
                ('scenes', models.JSONField()),
                ('characters', models.JSONField()),
                ('pdf_format', models.FileField(upload_to='scripts/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('scripts', models.ManyToManyField(default='NULL', to='core.scripts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
