# Generated by Django 5.0.1 on 2024-01-12 07:41

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sci-fi', 'Science Fiction'), ('horror', 'Horror'), ('fantasy', 'Fantasy'), ('romance', 'Romance')], max_length=1000, null=True),
        ),
    ]
