# Generated by Django 5.0.1 on 2024-01-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scripts_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripts',
            name='genres',
        ),
    ]
